### ISSUE TITLE
Upgrade from 3.4 to 4.0

### ISSUE THREAD

**Issue by average-joe** [dj-wasabi/ansible-zabbix-server#115]
**Describe the bug**

I'm trying to upgrade my current zabbix server from 3.4.11 to 4.0.  When using this role, I notice the following task doesn't *upgrade* my zabbix-server-mysql package:
```
- name: "RedHat | Installing zabbix-server-{{ zabbix_server_database }}"
  yum:
    pkg: "{{ zabbix_server_package }}"
    state: present
  tags:
    - zabbix-server
```
As a result, when Zabbix tries to restart, it fails.  There are unknown variables in the `zabbix-server.conf` preventing the service from starting.  

**Installation method/version**

* Github / Master

**Ansible Version**
* ansible version 2.7 

**Targetted hosts**
Concerns the following OS(es):

* CentOS

**Expected behavior**

At the completion of the task, zabbix-server service should successfully restart.
 
**Additional context**

To validate, after manually installing the latest `zabbix-server-mysql` package, zabbix-server service does successfully restart.
