### ISSUE TITLE
sign_keys not found

### ISSUE THREAD

**Issue by ramo-karahasan-riechardt** [dj-wasabi/ansible-zabbix-server#117]
Hi,

I'm running the latest Ubuntu 18.04 and ansible 2.6.5
I've installed this role via ansible-galaxy  and have the following playbook:

ansible-galaxy install dj-wasabi.zabbix-server

```
- name: Install Zabbix Server
  become: yes
  tags:
    - zabbix_server
  hosts: monitoring_elk
  roles:
    - role: dj-wasabi.zabbix-server
      database_type: "{{ zabbix_server_database }}"
      database_type_long: "{{ zabbix_server_database_long }}"
  vars:
    zabbix_server_name: "iws-monitoring"
    zabbix_server_database: "pgsql"
    zabbix_server_database_long: "postgresql"
    zabbix_server_dbhost: "{{ hostvars[groups.monitoring_elk[0]].ansible_default_ipv4['address'] }}"
    zabbix_server_dbname: "iws_monitoring"
    zabbix_server_dbuser: "iws01"
    zabbix_server_dbpassword: "f2l9fdhj8fFHI$=§w0fy0Zne"
    zabbix_server_dbport: "5432"
    zabbix_server_database_creation: true
    zabbix_version: 4.0
```

When I'm exectuing this, it ends up with the following message:
`FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'sign_keys' is undefined\n\nThe error appears e/roles/dj-wasabi.zabbix-server/tasks/Debian.yml'`
