### ISSUE TITLE
Security problem config file

### ISSUE THREAD

**Issue by kvakanet** [dj-wasabi/ansible-zabbix-server#126]
Hello!

```
- name: "Configure zabbix-server"                                                                                                                                                                           
  template:                                                                                                                                                                                                 
    src: zabbix_server.conf.j2                                                                                                                                                                              
    dest: /etc/zabbix/zabbix_server.conf                                                                                                                                                                    
    owner: zabbix                                                                                                                                                                                           
    group: zabbix                                                                                                                                                                                           
    mode: 0644                                                                                                                                                                                              
  notify:                                                                                                                                                                                                   
    - zabbix-server restarted                                                                                                                                                                               
  tags:                                                                                                                                                                                                     
    - zabbix-server                                                                                                                                                                                         
    - init                                                                                                                                                                                                  
    - config     
```
Mode file 0644 not good, may be 0640 .
Same thing in zabbix-web role.
