### ISSUE TITLE
Seboolean Error

### ISSUE THREAD

**Issue by average-joe** [dj-wasabi/ansible-zabbix-server#134]
**Describe the bug**
When running the latest update, the playbook is failing on this task:
```
- name: "RedHat | Enable httpd_can_connect_zabbix SELinux boolean"
  seboolean:
    name:
      - httpd_can_connect_zabbix
    state: yes
    persistent: yes
  when:
    - selinux_allow_zabbix_can_http
  tags:
    - zabbix-server
```
The resulting error is:
```
FAILED! => {"changed": false, "msg": "SELinux boolean ['httpd_can_connect_zabbix'] does not exist."}
```
Has anyone seen this error before?  Any ideas for resolution?

**Installation method/version**

* Github / latest

**Ansible Version**
* 2.7.0

**Targetted hosts**
Concerns the following OS(es):
* CentOS 7

**Expected behavior**
For the task to be completed successfully.  

**Additional context**
When attempting to run this manually on the host I do not get an error:
`setsebool -P httpd_can_connect_zabbix 1`
